name: smth_prototype_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  csv: ^5.0.2
  datepicker_dropdown: ^0.0.7+5
  dropdown_button2: ^2.3.7
  excel: ^2.1.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.0.15
  share_plus: ^7.1.0
  uuid: ^3.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
